#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'script.sh' using that other shell's path.
#
#       POSIX mode: /bin/sh -c "."
#
#   (2) The script will look for a command named 'java' in your PATH. If it
#       is not found, then try 'JAVA_HOME' environment variable.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before the first iteration,
        # so we can safely expand the args.
        set -- "$@" "$arg"
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; in
#     POSIX mode it's not recommended to do 'set -- "$var"' with "$var" having
#     quoted elements because the quotes will be treated literally, but it works
#     as long as the variable is not intended to be a portable POSIX one.
#     For example, setting 'foo='bar'baz' results in "$foo" being interpreted
#     as "barbaz" (unquoted) in POSIX, while in bourne shell it is "bar'baz"
#     (quoted).  POSity, let's not risk it and use a function to write
#     the args array explicitly.
#
# Note: the original author of this script recommended using array variables
# for the arguments array.  We'll go with that choice for consistency, and
# because it makes the code a little more understandable.
# See https://www.shellcheck.net/wiki/Sc2128
set_args () {
    local arg
    DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
    JAVA_OPTS=$JAVA_OPTS
    GRADLE_OPTS=$GRADLE_OPTS

    # Handle extra arguments that are in the environment variables
    # Split up in the same way as the standard Java command.
    # ShellCheck SC2086 is disabled because we want to splitting here.
    # shellcheck disable=SC2086
    set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "$@"

    # Add the arguments to the array, using IFS to split on spaces.
    # The leading space is to avoid "set --" treating the first item
    # specially.  This is consistent with how bash sees the arguments.
    # shellcheck disable=SC2046,SC2086,SC2068,SC2034
    IFS=" "
    printf -v arg_str "%s " "$@"
    # Trim off the trailing space and use the resulting string to
    # set the array.
    arg_str="${arg_str% }"
    set -- $arg_str

    # Determine the Java command options from the argument list.
    # We only keep the Java options (i.e., starting with -)
    # and the classpath, the rest are for the Gradle execution.
    java_args=
    classpath_libs=
    for arg
    do
        case $arg in
            -D*|-J*)
                java_args="$java_args \"$arg\""
                ;;
            -classpath)
                # Consume the next argument
                shift
                classpath_libs="$classpath_libs \"$1\""
                ;;
            -cp)
                # Consume the next argument
                shift
                classpath_libs="$classpath_libs \"$1\""
                ;;
            --)
                # Stop processing Java arguments
                shift
                break
                ;;
            *)
                # We can't distinguish whether this is a Gradle argument, a Java
                # option, or a classpath entry.  So, we add it all to the
                # classpath.
                classpath_libs="$classpath_libs \"$arg\""
                ;;
        esac
        shift
    done

    # Build the command line for the Java application.
    java_cmd="\"$JAVACMD\""
    # Add the classpath.
    if [ -n "$classpath_libs" ] ; then
        java_cmd="$java_cmd -classpath $classpath_libs"
    fi
    # Add the Java options.
    if [ -n "$java_args" ] ; then
        java_cmd="$java_cmd $java_args"
    fi
    # Add the main class.
    java_cmd="$java_cmd org.gradle.wrapper.GradleWrapperMain"

    # Add the rest of the arguments
    set -- "$@" "$java_cmd"
    shift
    # shellcheck disable=SC2086
    set -- $java_cmd "$@"
}

# Apply the JVM options and run the command
set_args "$@"
eval exec '"$@"'